# Generated by Django 5.2.7 on 2025-10-17 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='logo_path',
        ),
        migrations.AddField(
            model_name='projects',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='project_logos/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='manager',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
