# Generated by Django 5.2.7 on 2025-10-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projects_logo_path_projects_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
