# Generated by Django 5.2.7 on 2025-10-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-created_at']},
        ),
    ]
