# Generated by Django 5.2.7 on 2025-10-17 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bugs',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='bug_attachment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature Request'), ('task', 'Task')], default='bug', max_length=20),
        ),
    ]
