# Generated by Django 5.2.7 on 2025-10-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_alter_bugs_unique_together_alter_bugs_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('started', 'Started'), ('resolved', 'Resolved'), ('completed', 'Completed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature')], default='bug', max_length=20),
        ),
    ]
