# Generated by Django 5.2.7 on 2025-10-20 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_alter_bugs_status_alter_bugs_title_alter_bugs_type'),
        ('projects', '0002_remove_projects_logo_path_projects_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugs',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='bugs',
            unique_together={('project', 'title')},
        ),
        migrations.AddField(
            model_name='bugs',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='bug_screenshots/'),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='detail',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bugs',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='bugs',
            name='bug_attachment',
        ),
    ]
