# Generated by Django 5.2.7 on 2025-10-21 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_alter_bugs_options_alter_bugs_unique_together_and_more'),
        ('projects', '0002_remove_projects_logo_path_projects_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugs',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='bugs',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bugs',
            name='bug_attachment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_bugs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='bugs',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='unique_bug_title_per_project'),
        ),
        migrations.RemoveField(
            model_name='bugs',
            name='screenshot',
        ),
    ]
