# Generated by Django 5.2.7 on 2025-10-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_alter_bugs_options_alter_bugs_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugs',
            options={'ordering': ['-created_at']},
        ),
    ]
